type Query {
    hello(name: String): String
    employee: Employee
    employees: [EmployeeDto]
    employeeById(id: ID!): EmployeeDto
}

type Mutation {
    createEmployee(input: EmployeeCreateDto!): EmployeeDto 
    updateEmployee(id: ID!, input: EmployeeUpdateDto!): EmployeeDto
    deleteEmployee(id: ID!): String
}


input EmployeeUpdateDto {
    name: String!
    salary: Float!
}

input EmployeeCreateDto  {
    name: String!
    salary: Float!
}


type EmployeeDto{
 	id: ID
	name: String
	salary: Float
}

type Employee {
	id: ID
	name: String
	salary: Float
}