type Query {
    hello(name: String): String
    employee: Employee
    employeeById(id: ID!): EmployeeDto
    #old Implementation
    #employees: [EmployeeDto]
    # Pagination implementation
   # employees(page: Int!, size: Int!): EmployeePage
   #sortBy is a filter here for example sorytBy salary in asec or desc
   employees(page:Int!,size:Int!,sortBy:String = "name",direction:String="DESC"): EmployeePageDto
   getDepartmentDto(id: ID!): DepartmentDto
  
}

type Mutation {
    createEmployee(input: EmployeeCreateDto!): EmployeeDto 
    updateEmployee(id: ID!, input: EmployeeUpdateDto!): EmployeeDto
    deleteEmployee(id: ID!): String
}



input EmployeeUpdateDto {
    name: String!
    salary: Float!
   # department: DepartmentDto!
}

input EmployeeCreateDto  {
    name: String!
    salary: Float!
    # department: DepartmentDto!
}


type EmployeeDto{
 	id: ID
	name: String
	salary: Float
	department: DepartmentDto
}

type EmployeeSummaryDto{
    id: ID
	name: String
	salary: Float
}


type DepartmentDto{
	id: ID
	name: String
	employees: [EmployeeSummaryDto]
}

type Employee {
	id: ID
	name: String
	salary: Float
}

type EmployeePageDto {
    content: [EmployeeDto]
    totalElements: Int
    totalPages: Int
    pageNumber: Int
    pageSize: Int
    first: Boolean
    last: Boolean

}

